spring:
  application:
    name: catalog
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${profile:dev}

 #Banco de dados MySQL
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/microcatalog
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true